### ISSUE TITLE
Pipfile Typo

### ISSUE THREAD

**Issue by jgilberstadt** [ccipd/MRQy#11]
Hello,

I noticed that there is a single quote on line 17 of the pipfile that is supposed to be a double quote. I received an error message when running the original pipfile, but everything seems to work if the single quote is changed to a double quote.

Thanks,
Josh

**Comment by satishev** [comment]
@Amir-Reza-Sadri will look into this shortly.

**Comment by Amir-Reza-Sadri** [comment]
The issue is fixed. Thanks.
