### ISSUE TITLE
Front-end View Problem Loading Images

### ISSUE THREAD

**Issue by jgilberstadt** [ccipd/MRQy#12]
Hello,

It seems like the front-end view is only able to load images that are stored in the UserInterface subdirectory of the main MRQy directory. Is the front-end view supposed to be capable of loading images stored outside the UserInterface subdirectory, and if it is then how can those images be loaded?

Thanks,
Josh

**Comment by satishev** [comment]
MRQy generates PNGs (I think) when processing the cohort, and stores those in the UserInterface directory. The front-end is basically an HTML file, which loads in images through the image_init JS file. Paths would have to set in there to use a different source directory for images.

**Comment by Amir-Reza-Sadri** [comment]
In the second line of the “results.tsv” file change the #outdir location of the loaded images to the desired path.

**Comment by jgilberstadt** [comment]
Thank you for the replies. It looks like DATA_PATH is initialized with rel_outdir, so initializing it with abs_outdir should allow the user to open the images in any directory.

**Comment by Amir-Reza-Sadri** [comment]
You can change the DATA_PATH default value in the MRQy/UserInterface/scripts/global_config.js line 6.
