### ISSUE TITLE
sample_size error 

### ISSUE THREAD

**Issue by RiccardoPederzolli** [ccipd/MRQy#2]
Hello everyone,
I was trying to use your tool to analize some data but it seems I can't make it work.
I have followed the steps in the wiki but theese are the outputs.
I have also tried to manually insert the sample size value but the output is the same.

Python version is 3.6.9

![image](https://user-images.githubusercontent.com/63670179/106500470-29a45280-64c2-11eb-8cf7-65837e728408.png)

![image](https://user-images.githubusercontent.com/63670179/106500711-6e2fee00-64c2-11eb-8b39-e20ebbce030b.png)

Do you have any idea of what can it be?
Thank you for your help.

**Comment by satishev** [comment]
@Amir-Reza-Sadri will look into this and get back to you.

**Comment by Amir-Reza-Sadri** [comment]
@Cantagallo494: Please use the updated version of the codes. It should be work now. Thank you

**Comment by Cantagallo494** [comment]
Thank you for your reply.
"pipenv install ." works and installs all the dependencies 
"python -m mrqy.QC --help" gives the same error
"src\mrqy\QC.py out_dir in_dir" seems to work just fine. I'll try to run it on a full dataset and check the results.

Thank you very much. Keep up the good work
