### ISSUE TITLE
Parallel

### ISSUE THREAD

**Issue by kJONN** [ccipd/MRQy#20]
In our study we have thousands of scan sessions and I would like to run these in parallel. It seems though that the results.tsv file gets newly remade with every parallel run of the program. Is there a way to append to it while running it simultaneously? it seems that in the participant folder only the png files are saved and not any participant data that can be extracted afterwards in one go.
Thanks.

**Comment by satishev** [comment]
Looping in @Amir-Reza-Sadri

**Comment by Amir-Reza-Sadri** [comment]
If I understand correctly in the front-end you can use the table control right after each table, use deselect button to remove undesired cases, and then save them to new results.tsv file.

**Comment by satishev** [comment]
Each parallel run is generating TSV files.. can't all the TSV files just be concatenated into a single TSV file which can then be passed into the HTML interface?

**Comment by kJONN** [comment]
I will generate the output to different dirs then and concatenate the TSVs. That is a very workable solution.
Thank you for your assistance!
