### ISSUE TITLE
QC.py npt recognized

### ISSUE THREAD

**Issue by drkitty28** [ccipd/MRQy#22]
This looks great and exactly what I need, but can't get past the install.  I'm using Ubuntu 20.04, python 3.8

I followed the README instructions and I can launch the shell - setting up in my home .local directory
 .local/share/virtualenvs/MRQy-yxYQvYdT/bin/activate

I can install mrqy 
      pipenv install .
      Installing ....
      Adding mrqy to Pipfile's [packages]...
      ✔ Installation Succeeded 
      Installing dependencies from Pipfile.lock (829554)...

and I can get the help to output to the screen
      python -m mrqy.QC --help
      usage: QC.py [-h] [-r R] [-s S] [-b B] [-u U] [-t T] [-c C] output_folder_name [inputdir [inputdir ...]]

But, when I try to run "pipenv run -m pytest tests/"  I get "Error: the command -m could not be found within PATH or Pipfile's [scripts]."

What PATH variable is it looking for? There seems to be a PATH that was created in the .local/share/virtualenvs directory

Any help would be greatly appreciated.  And, yes, I did pip install the requirements.txt without issue.

**Comment by drkitty28** [comment]
Hi, I really need to get this working.  Can someone please help?

**Comment by Amir-Reza-Sadri** [comment]
I am working on this error. Meantime can you download the QC.py and QCF.py scripts and run them without using the mrqy env?

**Comment by drkitty28** [comment]
Where are the scripts?

**Comment by drkitty28** [comment]
OK, I found scripts under the build/lib/mrqy directory.  Tried running in the mrqy shell and got "command not found" - Also, tried importing mrqy in python and running and got "no mdoule named mrqy"  -  So, I'm at a loss.

**Comment by Amir-Reza-Sadri** [comment]
In the QC.py code uncomment line#11 and comment line#12.

**Comment by drkitty28** [comment]
OK, closer.  I'm testing with OpenNeuro images and I think they may be corrupted re error message.  I'll try with my own data and update status

MRQy is starting....
The number of patients is 12
Traceback (most recent call last):
  File "QC.py", line 358, in <module>
    v = volume_notdicom(k, nondicom_names[l])
  File "QC.py", line 144, in volume_notdicom
    image_data, image_header = load(scan)
  File "/home/cat/.local/lib/python3.8/site-packages/medpy/io/load.py", line 106, in load
    raise ImageLoadingError('The supplied image {} does not exist.'.format(image))
medpy.core.exceptions.ImageLoadingError: The supplied image /home/cat/MRQy/sub-001/func/sub-001_task-sitrep_run-06_bold.nii.gz does not exist.

**Comment by drkitty28** [comment]
Tried running pytest re the README file but got an error where it can't find the -m

pipenv run -m pytest tests/
Creating a virtualenv for this project...
Pipfile: /home/cat/APPS/MRQy/build/lib/mrqy/Pipfile
Using /home/cat/.local/share/virtualenvs/MRQy-yxYQvYdT/bin/python (3.8.10) to create virtualenv...
⠋ Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 1140ms
  creator Venv(dest=/home/cat/.local/share/virtualenvs/mrqy-6GTtRS1Y, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Posix)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/cat/.local/share/virtualenv)
    added seed packages: pip==22.3.1, setuptools==65.5.1, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/cat/.local/share/virtualenvs/mrqy-6GTtRS1Y
Creating a Pipfile for this project...
Error: the command -m could not be found within PATH or Pipfile's [scripts].

**Comment by drkitty28** [comment]
"python -m mrqy.QC --help" seems to look for the module in ".local/share/virtualenvs/MRQy-yxYQvYdT/lib/python3.8/site-packages"  But neither mrqy.QC or QC seems to be there.   Another user had a similar problem (https://github.com/ccipd/MRQy/issues/3)  which is probably why you had me comment out line11 and uncomment line12.  But, this is not fixing the problem for me.  Where are the modules stored?

**Comment by Amir-Reza-Sadri** [comment]
Could you please share some of your data?
ars329@case.edu

**Comment by drkitty28** [comment]
I've tried different data sets with no luck.  But, the wiki suggested the TCIA data which I tried.  How would I share that as it's locally downloaded and probably too big to attach here.  What's the minimum data needed for the MRQy to work?

**Comment by Amir-Reza-Sadri** [comment]
6 patients of your dataset share via email or google drive. What were the last error and the approach you tried?

**Comment by drkitty28** [comment]
Here are screenshots of the TCIA directory, the QCpy_Script, the directory structure,  the pipenv install, and the code testing.  Is there some particular structure that the data directory should have?  the QC.py script appears  in several locations  (app directory  & virturalenv). Which should be modified?  There seems to be an issue with the directory structure or the QC.py code usage.  

![codeTesting](https://user-images.githubusercontent.com/26172078/202187964-e10dbf66-904e-4c6d-9dc3-418d966df484.png)
![MQRy_testing](https://user-images.githubusercontent.com/26172078/202187969-ad0a25ee-c03f-474d-952d-b4f9179fc345.png)
![MRQy_dir_structure](https://user-images.githubusercontent.com/26172078/202187971-16192de3-0957-4fa9-a6aa-09d27790e228.png)
![QCpy_Script](https://user-images.githubusercontent.com/26172078/202187973-5d9adff8-5cbd-417b-b65b-06e978fbb107.png)
![TCIA_directory](https://user-images.githubusercontent.com/26172078/202187976-c7a3c739-d8ae-46ca-9af8-b868344fe99b.png)

**Comment by drkitty28** [comment]
Here are screenshots of the TCIA directory, the QCpy_Script, the directory structure,  the pipenv install, and the code testing.  Is there some particular structure that the data directory should have?  the QC.py script appears  in several locations  (app directory  & virturalenv). Which should be modified?  There seems to be an issue with the directory structure or the QC.py code usage.  

![codeTesting](https://user-images.githubusercontent.com/26172078/202187964-e10dbf66-904e-4c6d-9dc3-418d966df484.png)
![MQRy_testing](https://user-images.githubusercontent.com/26172078/202187969-ad0a25ee-c03f-474d-952d-b4f9179fc345.png)
![MRQy_dir_structure](https://user-images.githubusercontent.com/26172078/202187971-16192de3-0957-4fa9-a6aa-09d27790e228.png)
![QCpy_Script](https://user-images.githubusercontent.com/26172078/202187973-5d9adff8-5cbd-417b-b65b-06e978fbb107.png)
![TCIA_directory](https://user-images.githubusercontent.com/26172078/202187976-c7a3c739-d8ae-46ca-9af8-b868344fe99b.png)

**Comment by drkitty28** [comment]
Got MQRy to run and create a report!  This was on a single subject's anatomical.  MQRy didn't seem to like the nii.gz format for the functional data.  Is the compressed .nii format acceptable for MQRy or must it be uncompressed - .nii only?  
![MRQy_RunReport](https://user-images.githubusercontent.com/26172078/202219949-f375095b-ab36-4c94-9b71-2897979874ff.png)

**Comment by drkitty28** [comment]
Having a problem with functional (BOLD) images.  I use a known 4D BOLD image as input (tried a couple different ones), but get the error below.  What's meant by "third dimension must be 3 or 4"?

![image](https://user-images.githubusercontent.com/26172078/202230341-a7346313-a96b-4202-8c0b-9bd7bfa93512.png)

**Comment by rongjiewang** [comment]
> Some progress... I started QC.py from the "MRQy/src/mrqy" directory while in the MRQy shell. I used the "tests//TCIA" directory as the input and "tests" as the output. MRQy started but produced an error about "input arrays having the same shape" - No idea what this means. The TCIA data was in the download from git. What are the constraints on the data MRQy has? How to make the array size the same? The array size of what exactly? ![QCpy_test](https://user-images.githubusercontent.com/26172078/202209159-a5dcb744-4d3a-4c07-9b3b-d835dc3602f0.png)

I have the same problem.

**Comment by Amir-Reza-Sadri** [comment]
Can you share some of your data?

**Comment by Amir-Reza-Sadri** [comment]
Please add -r "True" flag at the end of your synax when you run the code.
