### ISSUE TITLE
DATA

### ISSUE THREAD

**Issue by PadarthiNitheesh** [ccipd/MRQy#31]
How can i get the TSV file and Data set for seeing the result

**Comment by Amir-Reza-Sadri** [comment]
This type of metric is already available in the IQM.csv file. You can find it there to see the results you're interested in.

**Comment by PadarthiNitheesh** [comment]
Can you send me the result tsv file from me please

**Comment by Amir-Reza-Sadri** [comment]
When you run the code over your data, the .tsv file will be generated automatically.

**Comment by PadarthiNitheesh** [comment]
Where should I run the local development and what type of data should I
have to take
