### ISSUE TITLE
perplexity must be less than n_samples

### ISSUE THREAD

**Issue by drkitty28** [ccipd/MRQy#33]
Running QC4d.py on 4D BOLD images produces this error. Could you explain what's wrong?  A tgz file is produced, but  neither the t-SNE or UMAP plots are created.  Thanks for your help.
![Screenshot from 2023-11-19 13-18-16](https://github.com/ccipd/MRQy/assets/26172078/3806ce21-5c40-45b7-9b0a-9b3b5ad06e95)

**Comment by drkitty28** [comment]
Got the same thing when running the TCIA test data
![Screenshot from 2023-11-19 14-05-57](https://github.com/ccipd/MRQy/assets/26172078/18bacd4a-dce8-4104-bb4a-f4d4e05252f4)

**Comment by Amir-Reza-Sadri** [comment]
you can change the perplexity number in line #380 from QC.py.

**Comment by mohsenhariri** [comment]
Resolved.
