### ISSUE TITLE
Lung MRI project 

### ISSUE THREAD

**Issue by aranmaro** [ccipd/MRQy#5]
Hello 
 
 I am trying to apply your tool for the Lung MR imaging.
I has been looking for a tool to get some quantitative values such as SNR, CNR from the before and after denoising to Lung MR images.
And finally, your MRQy gives me what I've been looking for. Yes, it works very successfully.  ( thank you again for your great work!!)
But I think I'd better to check (because it's Lung MR , zero TE image) whether it selects lung correctly.
I just want to see overlay mask to see what's selected for foreground iamges  because...the Lung itself has lower signal compare to the other surrounding muscle and fat.
Please check the Lung MR images if you want, "Comparison of lung imaging using three-dimensional ultrashort echo time and zero echo time sequences: preliminary study"

At this point, I wonder if there is any way to extract the"selected foreground  and background boundary, overlay mask" ,
Also, can I extract  "MEAN  of background" with MEAN of foreground , together ?
Those two information will be important to check whether it successfully worked to the Lung MR or not.

Any comment and advice would be very appreciated.
best regards
Moonjung

**Comment by Amir-Reza-Sadri** [comment]
Thank you for using MRQy. If you see the [wiki](https://github.com/ccipd/MRQy/wiki) page you can have access to the foreground mask by setting its flag. Please note that you can always use your foreground detection algorithm in the baseline of the MRQy pipeline.

**Comment by satishev** [comment]
@aranmaro Please let us know if the above fixed your issue, closing this for now.
